// Importing this will register all custom elements for the components
import './fds-action-sheet.js'
import './fds-alert.js'
import './fds-button.js'
import './fds-card.js'
import './fds-checkbox.js'
import './fds-combobox.js'
import './fds-dialog.js'
import './fds-divider.js'
import './fds-dropdown.js'
import './fds-icon.js'
import './fds-input.js'
import './fds-navigation.js'
import './fds-popover.js'
import './fds-table.js'
