// Importing this will register all custom elements for the components
import './fds-action-sheet'
import './fds-alert'
import './fds-button'
import './fds-card'
import './fds-checkbox'
import './fds-combobox'
import './fds-dialog'
import './fds-divider'
import './fds-dropdown'
import './fds-icon'
import './fds-input'
import './fds-navigation'
import './fds-popover'
import './fds-table'
