name: build, lint, test
on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
    branches:
      - main
  pull_request:
    paths:
      - frontend/**
jobs:
  build:
    name: build, lint, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: build, lint, test
        run: | 
          npm ci
          npm run build
          npm run lint
          npm run test
